language: android
dist: trusty
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-27

licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+

before_install:
  - chmod +x gradlew
script:
  - ./gradlew assembleRelease

before_deploy:
  - cp app/build/outputs/apk/release/*-release.apk ~
  - export APK_PATH=$(readlink -f ~/*-release.apk)
  - echo $APK_PATH

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: $APK_PATH
  overwrite: true
  on:
    tags: true
